import dash
from dash import dcc, html, dash_table, Input, Output
import dash_bootstrap_components as dbc
import pandas as pd
import plotly.express as px

# ---------------------------------------------------------------------------
# 1. DATA LOADING & PREPARATION
# ---------------------------------------------------------------------------
def load_data():
    # Replace with your actual Excel filename
    # Reads the columns generated by your SQL query aliases
    df = pd.read_excel("overdueInspections.xlsx")
    
    # Ensure dates are parsed correctly
    date_cols = ['Actual Due Date', 'Last Event Date', 'In Service Date', 'Planned Event Date']
    for col in date_cols:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce').dt.date

    # Fill missing values for clean filtering
    df['Months Overdue'] = pd.to_numeric(df['Months Overdue'], errors='coerce').fillna(0)
    df['Equipment Type'] = df['Equipment Type'].fillna('Unknown')
    df['Operating Status'] = df['Operating Status'].fillna('Unknown')
    
    return df

df_clean = load_data()

# ---------------------------------------------------------------------------
# 2. APP INITIALIZATION & LAYOUT
# ---------------------------------------------------------------------------
# Using a clean, professional Bootstrap theme
app = dash.Dash(__name__, external_stylesheets=[dbc.themes.FLATLY])

app.layout = dbc.Container([
    # Header Banner
    dbc.Row([
        dbc.Col(html.H1("Equipment Maintenance & Reliability Dashboard", 
                        className="text-center text-white p-3 bg-primary rounded-bottom"), width=12)
    ], className="mb-4"),

    # KPI Cards Row
    dbc.Row([
        dbc.Col(
            dbc.Card([
                dbc.CardBody([
                    html.H5("Total Equipment Listed", className="card-title text-muted"),
                    html.H2(f"{len(df_clean):,}", className="text-primary font-weight-bold")
                ])
            ], className="shadow-sm border-0"), width=4
        ),
        dbc.Col(
            dbc.Card([
                dbc.CardBody([
                    html.H5("Overdue Items (0+ Months)", className="card-title text-muted"),
                    html.H2(f"{len(df_clean[df_clean['Months Overdue'] > 0]):,}", className="text-danger font-weight-bold")
                ])
            ], className="shadow-sm border-0"), width=4
        ),
        dbc.Col(
            dbc.Card([
                dbc.CardBody([
                    html.H5("Critical Deferrals Active", className="card-title text-muted"),
                    html.H2(f"{len(df_clean[df_clean['Needs Deferral'] == 1]):,}", className="text-warning font-weight-bold")
                ])
            ], className="shadow-sm border-0"), width=4
        ),
    ], className="mb-4"),

    # Filters and Graph Row
    dbc.Row([
        # Filter Sidebar
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.H5("Data Filters", className="card-title mb-3"),
                    html.Label("Filter by Equipment Type:"),
                    dcc.Dropdown(
                        id="type-dropdown",
                        options=[{"label": t, "value": t} for t in sorted(df_clean['Equipment Type'].unique())],
                        multi=True,
                        placeholder="All Equipment Types",
                        className="mb-3"
                    ),
                    html.Label("Filter by Area ID:"),
                    dcc.Dropdown(
                        id="area-dropdown",
                        options=[{"label": str(a), "value": a} for a in sorted(df_clean['Area ID'].dropna().unique())],
                        multi=True,
                        placeholder="All Areas"
                    ),
                ])
            ], className="shadow-sm border-0 h-100")
        ], width=3),

        # Interactive Chart
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.H5("Overdue Status Breakdown", className="card-title"),
                    dcc.Graph(id="overdue-bar-chart")
                ])
            ], className="shadow-sm border-0")
        ], width=9)
    ], className="mb-4"),

    # Data Table Row
    dbc.Row([
        dbc.Col([
            dbc.Card([
                dbc.CardBody([
                    html.H5("Master Scheduler Inspection Log", className="card-title mb-3"),
                    dash_table.DataTable(
                        id="data-table",
                        columns=[{"name": i, "id": i} for i in [
                            'Equipment ID', 'Description', 'Equipment Type', 
                            'Event Type', 'Last Event Date', 'Actual Due Date', 'Months Overdue'
                        ]],
                        page_size=10,
                        sort_action="native",
                        filter_action="native",
                        style_table={'overflowX': 'auto'},
                        style_cell={
                            'textAlign': 'left',
                            'padding': '10px',
                            'fontFamily': 'sans-serif',
                            'fontSize': '14px'
                        },
                        style_header={
                            'backgroundColor': '#2c3e50',
                            'color': 'white',
                            'fontWeight': 'bold'
                        },
                        style_data_conditional=[
                            {
                                'if': {
                                    'filter_query': '{Months Overdue} > 0',
                                    'column_id': 'Months Overdue'
                                },
                                'backgroundColor': '#f8d7da',
                                'color': '#721c24',
                                'fontWeight': 'bold'
                            }
                        ]
                    )
                ])
            ], className="shadow-sm border-0")
        ], width=12)
    ], className="mb-5")

], fluid=True)

# ---------------------------------------------------------------------------
# 3. INTERACTIVE CALLBACKS
# ---------------------------------------------------------------------------
@app.callback(
    [Output("overdue-bar-chart", "figure"),
     Output("data-table", "data")],
    [Input("type-dropdown", "value"),
     Input("area-dropdown", "value")]
)
def update_dashboard(selected_types, selected_areas):
    # Start with a copy of full data
    filtered_df = df_clean.copy()
    
    # Apply dropdown filters conditionally
    if selected_types:
        filtered_df = filtered_df[filtered_df['Equipment Type'].isin(selected_types)]
    if selected_areas:
        filtered_df = filtered_df[filtered_df['Area ID'].isin(selected_areas)]
        
    # Generate bar chart data (Aggregate by Type, showing average months overdue)
    if not filtered_df.empty:
        agg_df = filtered_df.groupby('Equipment Type', as_index=False)['Months Overdue'].mean()
        fig = px.bar(
            agg_df, 
            x='Equipment Type', 
            y='Months Overdue',
            labels={'Months Overdue': 'Avg Months Overdue'},
            color_discrete_sequence=['#e74c3c']
        )
        fig.update_layout(margin=dict(l=20, r=20, t=20, b=20), paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)')
    else:
        fig = px.bar(title="No data matches filter selection")

    return fig, filtered_df.to_dict('records')


# ---------------------------------------------------------------------------
# 4. EXECUTION
# ---------------------------------------------------------------------------
if __name__ == '__main__':
    app.run_server(debug=True, port=8050)
